version: '3.8'

services:
  server:
    build:
      context: .
      args:
        NODE_ENV: development
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./server:/app/src
      - /app/node_modules
    command: npm run dev
    ports:
      - "5000:5000"

  client:
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
