version: '3.8'

services: 
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server-app
    container_name: bindboard-node-server
    environment:
      NODE_ENV: production
    ports:
      - "5000:5000"
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-app
    container_name: bindboard-react-client
    ports:
      - "80:80"
    depends_on:
      - server
