version: '3.8'

services:
  server:
    environment:
      NODE_ENV: development
    ports:
      - "5000:5000"
    command: npm run dev

  client:
    ports:
      - "5173:5173"
    command: npm run dev
